# Generated by Django 5.0.6 on 2024-05-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarymanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
